### ISSUE TITLE
I can't figure out how to read/write a DO from index.svelte

### ISSUE THREAD

**Issue by bbigras** [tyvdh/boilerkit#1]
Sorry for the dumb question. I'm still new with Svelte and cloudflare kv/DO.

How can I read/write a DO from index.svelte?

I also don't understand the difference between

https://github.com/tyvdh/test-kit/blob/2fb660eaa29b0a0baa3b7f14b3238396cd9fe268/src/routes/index.js#L2-L7

and

https://github.com/tyvdh/test-kit/blob/2fb660eaa29b0a0baa3b7f14b3238396cd9fe268/src/helpers/do.js#L8

If I try `DO.idFromName('hello')`, should I get `world`?

**Comment by kalepail** [comment]
:P no worries. This isn't something that's specific to Svelte. For this question you'll want to consult the Cloudflare docs on Durable Objects.

https://developers.cloudflare.com/workers/runtime-apis/durable-objects/
https://developers.cloudflare.com/workers/learning/using-durable-objects/
